### PR TITLE
Update for upload to Debian

### PR DESCRIPTION
**Pull request by tfauck**
Here is the work for upload to debian 
$ lintian  -EviIL +pedantic 
N: Using profile debian/main.
N: Setting up lab in /tmp/temp-lintian-lab-dhutuIUCoq ...
N: Unpacking packages in group paflib/0.2.0-1.1
N: ----
N: Processing changes file paflib (version 0.2.0-1.1, arch source ppc64el) ...
N: ----
N: Processing source package paflib (version 0.2.0-1.1, arch source) ...
N: ----
N: Processing binary package libpaf-ebb0 (version 0.2.0-1.1, arch ppc64el) ...
N: ----
N: Processing binary package libpaf-dsc0 (version 0.2.0-1.1, arch ppc64el) ...
N: ----
N: Processing binary package libpaf-dev (version 0.2.0-1.1, arch ppc64el) ...

### CODE REVIEW

**Comment by gftg85** [comment]
Hi, Thierry,

Thanks for doing this. A couple of questions for you:

The third commit (918a8c1) looks weird. It removes the recently add ppr support. Then, the forth commit (ab0f292) reverts this. Could you redo your patch series without removing then re-adding ppr support?

Besides that, the first commit (863d57d) adds a lot of binary files into the debian subdirectory. Did you accidentally add them? Actually, it seems that the whole installation under the debian subdirectory has been accidentally added to git.

**Comment by tfauck** [comment]
On 02/09/2015 18:28, Gabriel Ferreira Teles Gomes wrote:
>
> Hi, Thierry,
>
> Thanks for doing this. A couple of questions for you:
>
> The third commit (918a8c1 
> <https://github.com/paflib/paflib/commit/918a8c19e2ddef6195529265db8e56b726d0d8e6>) 
> looks weird. It removes the recently add ppr support. Then, the forth 
> commit (ab0f292 
> <https://github.com/paflib/paflib/commit/ab0f29211ee5b1a80320503dd1efd007be7b7fc0>) 
> reverts this. Could you redo your patch series without removing then 
> re-adding ppr support?
>
> Besides that, the first commit (863d57d 
> <https://github.com/paflib/paflib/commit/863d57db7df4be1eaf2b4721fa3d464d133866da>) 
> adds a lot of binary files into the debian subdirectory. Did you 
> accidentally add them? Actually, it seems that the whole installation 
> under the debian subdirectory has been accidentally added to git.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/paflib/paflib/pull/12#issuecomment-137157372>.
>
Hello,
Yes sounds like something weird appeared - I will review the packaging 
and ensure all these problems are solved in order to clean situation. If 
I have questions I will ask before pushing again.
Thanks a lot for taking care of that.

Regards
Thierry

**Comment by tfauck** [comment]
Have uploaded to DEBIAN an updated and hoppefully fixed version of the debian sources 
gpg: Signature made Mon 14 Sep 2015 07:55:52 AM EDT using RSA key ID FCC181CE
gpg: Good signature from "Thierry Fauck (thf 2015) <tfauck@free.fr>"
Good signature on ../paflib_0.2.0-1.dsc.
Uploading to mentors (via ftp to mentors.debian.net):
  Uploading paflib_0.2.0-1.dsc: done.
  Uploading paflib_0.2.0.orig.tar.gz: done.
  Uploading paflib_0.2.0-1.debian.tar.xz: done.
  Uploading paflib_0.2.0-1_source.changes: done.
Successfully uploaded packages.

I have updated the https://github.com/tfauck/paflib_020.git

**Comment by gftg85** [comment]
Hi, Thierry.

Thanks for your update.

I noticed that you send your changes to another repository. Could you also update this pull request in this repository?

**Comment by tfauck** [comment]
Hi,
I am lost (currently pull request doesn't do anything because there is no real relation between paflib/paflib and tfauck/paflib_020). Would you mean I create a fork of paflib then add debian files and do a pull request ?

**Comment by gftg85** [comment]
Hi, Thierry.

Thanks for looking into it.

Indeed, tfauck/paflib_020 does not have any relationship with paflib/paflib. However, when you initially created this pull request, you were working on tfauck/paflib.git.

This repository (tfauck/paflib.git) does not exist, anymore. Have you delete it?

Anyway, that is not a problem, at all. :)

If you do as you just suggested, i.e.: create a fork of paflib then add debian files and do a pull request, I would very much appreciate it. :D 

If you believe that creating a new pull request is the best choice, please feel free to do it.

**Comment by tfauck** [comment]
Hello
I have recreated tfauck/paflib.git and created  the pull request.
Let me know if that works for you
Thanks
Thierry


On 09/15/2015 08:36 PM, Gabriel Ferreira Teles Gomes wrote:
> Hi, Thierry.
> 
> Thanks for looking into it.
> 
> Indeed, tfauck/paflib_020 does not have any relationship with
> paflib/paflib. However, when you initially created this pull request,
> you were working on tfauck/paflib.git.
> 
> This repository (tfauck/paflib.git) does not exist, anymore. Have you
> delete it?
> 
> Anyway, that is not a problem, at all. :)
> 
> If you do as you just suggested, i.e.: create a fork of paflib then add
> debian files and do a pull request, I would very much appreciate it. :D
> 
> If you believe that creating a new pull request is the best choice,
> please feel free to do it.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/paflib/paflib/pull/12#issuecomment-140493284>.
> 


-- 

__________________________________________________________________________
thf - Thierry Fauck - tfauck@free.fr>
/pubkey: 4096R/FCC181CE/
/fingerprint: 5CCF 6B82 DE4E E72A A40B B63E A153 BF4F FCC1 81CE/

**Comment by gftg85** [comment]
Thank you, Thierry. I will move the discussion to pull request 13

**Pull request closed without merging**
